###  -----------------------------------------------  LOCAL  -----------------------------------------------------


### Get the message: Hello World!
GET http://localhost:3000/

###################### BOOKS #############################

### Get all the books
GET http://localhost:3000/api/books

### Get book by ID
GET http://localhost:3000/api/books/68cd94b356eb35fd1106f9fc

### Create a new book
POST http://localhost:3000/api/books
Content-Type: application/json

{
  "title": "Clean Code",
  "author": "Robert C. Martin",
  "genre": "Programming",
  "year": 2008,
  "isbn": "9780132350884",
  "availableCopies": 4,
  "totalCopies": 5
}

###  -----------------------------------------------  RENDER  -----------------------------------------------------


### Get the message: Hello World!
GET https://cse341-t3-lv-1-w2.onrender.com

###################### BOOKS #############################

### Get all the books
GET https://cse341-t3-lv-1-w2.onrender.com/api/books

### Get book by ID
GET https://cse341-t3-lv-1-w2.onrender.com/api/books/9780232350878

### Create a new book
POST https://cse341-t3-lv-1-w2.onrender.com/api/books
Content-Type: application/json

{
  "title": "My Books",
  "author": "El Perrito Faldero",
  "genre": "Logic",
  "year": 2015,
  "isbn": "9780132350878",
  "availableCopies": 2,
  "totalCopies": 3
}

### Update a book
PUT https://cse341-t3-lv-1-w2.onrender.com/api/books/9780232350878
Content-Type: application/json

{
  "title": "My Books 3",
  "author": "El Perrito Faldero",
  "genre": "Logic",
  "year": 2008,
  "isbn": "9780232350878",
  "availableCopies": 2,
  "totalCopies": 3
}

### Delete a book
DELETE https://cse341-t3-lv-1-w2.onrender.com/api/books/9780232350878
Content-Type: application/json


###################### USERS #############################