### LOCAL

### Get the message: Hello World!
GET http://localhost:3000/

### Get all the contacts
GET http://localhost:3000/api/contacts

### Get contact by ID
GET http://localhost:3000/api/contacts/68cd94b356eb35fd1106f9fc

### Create a new contact
POST http://localhost:3000/api/books
Content-Type: application/json

{
  "title": "Clean Code",
  "author": "Robert C. Martin",
  "genre": "Programming",
  "year": 2008,
  "isbn": "9780132350884",
  "availableCopies": 4,
  "totalCopies": 5
}

### RENDER

### Get the message: Hello World!
GET https://cse341-t3-lv-1-w2.onrender.com

### Get all the contacts
GET https://cse341-t3-lv-1-w2.onrender.com/api/contacts

### Get contact by ID
GET https://cse341-t3-lv-1-w2.onrender.com/api/contacts/68cd93fc56eb35fd1106f9f8

### Create a new contact
POST https://cse341-t3-lv-1-w2.onrender.com/api/contacts
Content-Type: application/json

{
  "title": "My Books",
  "author": "El Perrito Faldero",
  "genre": "Logic",
  "year": 2015,
  "isbn": "9780132350878",
  "availableCopies": 2,
  "totalCopies": 3
}

### Update a contact
PUT https://cse341-t3-lv-1-w2.onrender.com/api/contacts/68d454ed7cc05d69db61ddde
Content-Type: application/json

{
  "title": "My Books 3",
  "author": "El Perrito Faldero",
  "genre": "Logic",
  "year": 2008,
  "isbn": "9780232350878",
  "availableCopies": 2,
  "totalCopies": 3
}

### Delete a contact
DELETE https://cse341-t3-lv-1-w2.onrender.com/api/contacts/68cd94b356eb35fd1106f9fc
Content-Type: application/json
